---@class UIHauteCoutureDuplicateRewardBgGL:UICustomWidget
_class("UIHauteCoutureDuplicateRewardBgGL", UICustomWidget)
UIHauteCoutureDuplicateRewardBgGL = UIHauteCoutureDuplicateRewardBgGL

function UIHauteCoutureDuplicateRewardBgGL:Constructor()
end
