---@class UIHauteCoutureDuplicateRewardBgKR:UICustomWidget
_class("UIHauteCoutureDuplicateRewardBgKR", UICustomWidget)
UIHauteCoutureDuplicateRewardBgKR = UIHauteCoutureDuplicateRewardBgKR

function UIHauteCoutureDuplicateRewardBgKR:Constructor()
end
