---@class UISakuraTaskControllerWrapper:UIActivityEveSinsaTaskController
_class("UISakuraTaskControllerWrapper", UIActivityEveSinsaTaskController)
UISakuraTaskControllerWrapper = UISakuraTaskControllerWrapper
