---@class UIHauteCoutureDrawDynamicProbabilityBgGL:UICustomWidget
_class("UIHauteCoutureDrawDynamicProbabilityBgGL", UICustomWidget)
UIHauteCoutureDrawDynamicProbabilityBgGL = UIHauteCoutureDrawDynamicProbabilityBgGL

function UIHauteCoutureDrawDynamicProbabilityBgGL:Constructor()
end