---@class BuffTargetType
BuffTargetType = {
    None = 0,
    Self = 1, --自己
    SkillTarget = 2, --技能目标
    AllMonster = 3, --所有怪物
    OneGridMonster = 4, --单格怪
    MultiGridMonster = 5, --多格怪
    PetElement = 6, --元素abcd
    RandomMonster = 7, --随机x个怪
    AllPet = 8, --全部存活星灵
    Team = 9, --队伍
    AroundMonster = 10, --周围一圈怪物
    NotifyTarget = 11, --通知目标
    RegularBodyMonster = 12, --常规体型怪（单格、四格）
    MonsterHaventDragonMark = 13, --没有龙女印记的怪物
    TheOneLastHitMe = 14, --使我血量变化的人
    AllTrap = 15, --所有机关
    SkillTargetXScopeType = 16, --技能目标中的X方向
    PetJob = 17, --职业abcd
    AnyAlive = 18, --随机一个存活星灵
    AnyDead = 19, --随机一个死亡星灵
    LowHPPet = 20, --血量最少星灵
    HPBTPet = 21, --血量大于x的星灵
    EachPickUpScopeNearest = 22, --在每一次点选的范围内 最近的怪物
    EachPickUpScopeFarest = 23, --在每一次点选的范围内 最远的怪物
    RandomMonsterByLayer = 24, --根据Layer层数随机选择怪物
    BodyAreaGridElementCount = 25, --根据身形所占指定属性的格子数量添加（多格占几个就添加几次）
    SkillTargetSelectBuffByLayer = 26, --根据技能目标身上指定layerName的层数添加不同的buff
    SpecificPet = 27, --指定宝宝
    MonsterExceptBoss = 28, --怪物除了Boss
    MonsterOnlyBoss = 29, --Boss
    SkillTargetRandomByLayer = 30, --根据层数在范围内随机
    AlreadySelectData = 31, --根据存储的目标挂buff
    SelfLayerComboModX = 32,
    Trap = 33, --范围内的机关
    SkillHolderName = 34, --根据SkillHolderName
    SelectBuffByCasterLayer = 35, --根据施加者身上指定layerName的层数添加不同的buff
    Defender = 36, --被打的人
    AllTalePet = 37, --场上所有传说光灵
    AllNonTalePet = 38, --场上所有非传说光灵
    HPPercentHighestMonster = 39, --场上血量百分比最高的怪物，如果百分比相同，取当前血量最高，还相同就随机
    SkillScopeCenterPosMonster = 40, --技能中心格子上的怪物
    SelectMonsterID = 41, ---指定怪物ID
    PetCamp = 42,
    MonsterAI = 43, --指定怪物AI
    NonLeaderPetElement = 44, --6号的翻版，需求是不选中当前leader
    SkillTargetNoRepeatID = 45, ---同2号相同滤掉重复的ID
    RemoteTeamAllPet = 46, --敌方全体光灵
    MaxDamageDealerPetToSelf = 47, -- 对自己造成伤害最高的光灵
    NonCasterPetElement = 48, --非施法者的指定属性光灵
    MyTrap = 49, --施法者召唤的机关
    BodyAreaGridElementProp = 50, --根据身形所占指定属性的格子数量比例，概率选中添加
    BodyAreaGridFindElement = 51, --根据身形下有没有指定属性的格子添加或不添加
    SkillTargetBodyAreaGridElementProp = 52, --技能目标中 根据身形所占指定属性的格子数量比例，概率选中添加
    SkillTargetBodyAreaGridFindElement = 53, --技能目标中 根据身形下有没有指定属性的格子添加或不添加
    SkillTargetRandomBuff = 54, --根据配置的Buff列表和权重为技能目标随机Buff
    CasterTeamLeader = 55, --施法者（buff持有者）所属队长
    SkillTargetOtherMonster = 56, --技能目标外的怪物
    SkillTargetElement = 57, --技能目标中指定属性的
    SkillTargetElementAndOwnerBuff = 58, --技能目标指定属性的 and 有指定的buff
    AllAliveMonster = 59, --所有没有死亡标记且血量不为0的怪物单位
    CurrentTeamLeader = 60, --当前队伍队长
    CurrentTeamTail = 61, --当前队伍队尾
    AllPetAndFeatureHolder = 62, --（本方）所有光灵和模块技能的holder （黑拳赛词条修改攻击力，合击技holder也需要处理）
    SkillScopeCenterPosMonsterOnTrap = 63,--技能中心格子上的怪物(且格子上有指定机关)
    SpTrap = 64, --指定机关ID
    AddPartnerTmpTeam = 65, --加入伙伴时的临时队伍 替换 Team
    AddPartnerAllPartnerPet = 66, --加入伙伴时的伙伴光灵 替换 AllPet
    AddPartnerAllPartnerPetElement = 67, --加入伙伴时的伙伴光灵（符合属性） 替换 PetElement
    AddPartnerTmpPetJob = 68, ---加入伙伴时的临时队伍中职业abcd 替换 PetJob
    AddPartnerTmpAllTalePet = 69, --加入伙伴时的临时队伍中所有传说光灵  替换 AllTalePet
    AddPartnerTmpAllNonTalePet = 70, --加入伙伴时的临时队伍中所有非传说光灵  替换 AllNonTalePet
    OneGridMonsterInRange = 71, --技能范围内所有单格怪（包括黑拳赛敌方队伍）
    PartOfAllMonster = 72, --全场一半(可配)的怪物（随机、向上取整）
    RandCountMonsterWithBuff = 73, --有指定buff的怪物（随机N1~N2个）
    MonsterAICheckScopeHasTargetTrap = 74, --指定怪物AI的一定范围内是否存在指定机关
    Host = 75, --被自己附身的宿主
    TrapTypeInRange = 76,--根据cfg_trap的TrapType在技能范围内选取，仅限技能使用
    SelectMonsterIDInSkillRange = 77, --41的技能范围限制版
    PetJobsAndElement = 78, --指定职业和属性的光灵
    End = 999 --
}
_enum("BuffTargetType", BuffTargetType)

--仅用于pvp模式下的buff目标替换
PvPBuffTargetTable = {
    [BuffTargetType.RegularBodyMonster] = BuffTargetType.AllMonster,
    [BuffTargetType.MonsterExceptBoss] = BuffTargetType.AllMonster,
    [BuffTargetType.HPPercentHighestMonster] = BuffTargetType.AllMonster,
    [BuffTargetType.SelectMonsterID] = BuffTargetType.AllMonster,
    [BuffTargetType.MonsterAI] = BuffTargetType.AllMonster
}
