SkillViewPhaseType = {
    Instruction = 0, --指令类型
    AttackAnimation = 1, --攻击
    CastAnimation = 2, --施法
    OnHit = 3, --被击
    GridArray = 5, --格子阵列
    ScreenShake = 6, --震屏
    WaveGridArray = 7, --波浪形格子阵列效果
    RoleCG = 8, --角色Spine动画
    SquareRing = 9, --方环效果
    LRAttackAnimation = 10, --区分左右手的攻击
    FireAnimation = 11, --燃烧弹
    ImpactAnimation = 13, --撞击.诺德
    FlightVehicle = 15, --发出飞行器攻击
    TurnRoundFlightVehicle = 16, --回旋飞机器攻击
    AddGridEffect = 18, --特殊格子生成效果
    RoundGridDifferent = 19, --周围8+12个格子特效不同的效果
    AbsorbPieceAnimation = 20, --吸收格子
    TrajectoryAnimation = 21, --光球轨道
    FlashKnifeAndLine = 22, --刀光连线
    SummonTrap = 23, --召唤陷阱
    GridReturn = 24, --目标返回到角色身上
    RandAttack = 25, --刑拘娘灵魂冲击：随机打击
    RangeAttackAnimation = 26, --远程施法攻击,可攻击多人
    HitBack = 27, ---击退表现
    PullAround = 28, --牵引表现
    ShowWarningArea = 29, --显示预警区域
    ConvertElment = 30, --对手动转色的执行的转色效果
    ScopeForward = 31, --以玩家为中心沿着选择的范围递进到边缘,伤害并转色
    EffectLineFlyWithDirection = 32, --以玩家为中心沿着选择的范围移动到边缘,伤害
    Charge = 33, --蓄力
    SummonEverything = 34, --召唤一切
    AddBlood = 36, ---治疗回血
    Blink = 37, ---闪现
    RemoveEffect = 38, ---移除绑定特效
    TrainConvertElement = 39, ---火车转色
    TrainHitBack = 40, ---火车击退
    EffectRangeAttack = 41, ---范围攻击
    PlayAudio = 43, ---播放音效
    StoryTips = 45, ---播放Tips
    -- GridRangeEffect = 46, ---给定范围的所有格子播放特效 DISAVOWED
    LRAttackDifferentAnimation = 47, --区分左右手动作不同的攻击
    LeaveEnterBattleField = 48, ---离场入场表现
    PlayLoopAudio = 51, --播放循环音效，可以配置为终止循环音效
    PlayEffect = 52, --播放特效，可扩展
    WaveGridTransform = 53, --波浪形按列展开，带旋转，按层缩放
    ScopeForwardTransform = 54, --与ScopeForward类似，格子特效间隔播放，带旋转和缩放
    TwoWayFlightVehicle = 55, --双向飞行器，目前做的是向左向右飞行，后续可以扩展为任意两个方向
    PlayEffectAtSomeElementGrid = 56, --在某属性类格子上播放特效，比如在所有水格子上播放一个特效，可以扩展规则，比如是否要过滤怪物脚底
    ShowHideRole = 57, ---显示/隐藏角色
    PlayEffectAtGrid = 60, ---在指定格子坐标处释放特效
    GridSpread = 61, ---以施法者为中心向外展开的范围攻击(可扩展转色)，以单层或多层的菱形(可扩展方形)形状展开
    GridDark = 62, ---所有格子变暗/恢复
    Trajectory = 63, ---弹道： 单纯的只有弹道
    ScopeForwardByDistance = 64, ---以玩家为中心沿着选择的范围递进到边缘,递进的时候按照格子距中心的距离
    MultiGridEffect = 65, ---多格播放特效，支持【取格子数组的子集播放特效】【随机顺序播放特效】
    CenterFirst = 66, ---距离施法者距离1的统一释放一个挂在施法者身上的特效，其余格子在延迟后统一释放特效
    ScopeGroup = 67, ---按照范围组播放技能效果，范围必须是成组出现的
    AOEDamage = 68, ---逐个目标单体伤害
    MultiGridColumnAndRowCenterRandom = 69, ---樱龙使  选择多点，横列加在一起(3个选择点 6个刀光)  随机顺序 横列的中点播放，同一选择点范围 先打横 就不被列打
    ColumnForward = 70, ---乌列尔 纵向播放特效  先播放玩家同y的格子 和 y+1的格子 ,第二批再播放y-1 y+2的格子
    ConvertOccupiedGridPhase = 71, -- ConvertOccupiedGridElement，对判定需要转色的播放特效
    ScopeTrajectory = 72, -- 根据给定方向，从释放者开始到scope边缘推的弹道
    BombBullet = 73, --子弹飞行爆炸表现phase
    SacrificeTrapsAndDamage = 74, -- 销毁范围内特定机关，并造成(基础伤害 * (1.0f + 机关个数 x 倍率))的伤害
    MultiGridDamageTrace = 75, -- 从施法者面前开始，到目标位置为止的路径上播放2x2的特效，黑蹄用
    BulletFlyToCasterFromEdge = 76, --弹道从版边外飞向施法者 幽灵一阶群攻
    ContinueAttack = 77, --持续攻击
    SinkAllTarget = 78, --将所有目标拉下地面，克娜莉大招使用
    TrainResetElement = 79, -- 卡戎专用-大招重置格子
    MultiStageDamage = 80, -- 将一个伤害拆成多段伤害表现
    SphereTrajectoryMultiStageDamage = 81, -- 球型轨迹随机多段攻击目标（渡主动技）
    CircleFlyMultipleEffect = 82, --星灵头顶环形飞多个弹道特效到目标点 （焚霜座连锁技）
    SummonChessSoldier = 83, --召唤国际象棋兵
    TeleportAndSummonTrap = 84, ---雷雨夜使用的瞬移+召唤机关
    NormalAttackForAddBlood = 85, ---普攻加血
    ScopePushOrPull = 86, ---露比主动技 击退时，范围（十字或x）距玩家最近处（4个）播特效，后想最远处移动，会被阻挡；拉近时，表现相反；处理被击、击退和牵引
    MiejinRoll = 87, --小女孩灭尽龙的专属：灭尽龙挂件滚到版边+召唤机关+伤害+击退+滚回原位
    GatherThrowDamage = 88, --鬼王技能：聚集范围内的指定类型怪和光灵，然后将光灵瞬移到指定范围内随机位置并造成伤害，杀死指定类型怪
    AbsorbTrapsAndDamageByPickupTarget = 89, --雨森主动技：根据点选对象选择是否吸收机关并造成伤害
    FlotageTrajectory = 90, -- 先浮力上升，再轨迹攻击目标（贾尔斯连锁技）
    NormalAttackOnlyAnimation = 91, ---普攻只做动画表演
    CircularTrajectory = 92, --在指定挂点的环形范围内，根据伤害结果创建特效
    NormalAttackWithMove = 93, ---普攻在移动过程中
    Transposition = 94, --互换位置
    TrajectoryHitOnOwnTrapPos = 95, --符文刺客 从场外移到符文机关上 然后做攻击表现
    ZhongxuSummonTrapOrAttachFlag = 96, --仲胥主动技 召唤机关 或给怪物附加标记
    CasterRotationTrajectory = 97, --施法者转圈发射弹道，会将逻辑结果根据表现动作排序（凯雅连锁）
    DashTeleportWithPath = 98, --耶利亚 表现上依次冲到每个点
    ConvertDamageTeleportByLinkLine = 99, --蒂娜主动技表现
    ControlMonsterMoveAttackSummon = 100, --控制小怪移动攻击召唤机关
    DrillerSummonBaseMonster = 101, --N29钻探者boss 技能2 吸收机关切换形态（召唤底座）
    DrillerSacrificeTrapAndDamage = 102, --N29钻探者boss 技能3 吸收机关攻击目标
    DrillerExplosion = 103, --N29钻探者boss 技能4 爆炸，恢复单格
    DrillerExplosionSimple = 104, --N29钻探者boss 技能5 解体，恢复单格
    NightKingTeleportDamageWithPath = 105, --N30 夜王三阶段 连续冲刺伤害
    PetANaTuoLiTraction = 106, --N30 光灵阿纳托利主动技
    ScopeForwardTransformNoAttack = 107, --与ScopeForwardTransform一致 无攻击效果，播放转色不使用攻击范围
    ScopeForwardNoAttack = 108, --以玩家为中心沿着选择的范围递进到边缘,伤害并转色 = 107, --与ScopeForwardTransform一致 无攻击效果，播放转色不使用攻击范围
    Pet1602091Chain = 109, --SP雷霆高定连锁技表现
    Else = 9999 ---防止上面逗号被格式化
}
