---@class SkillEffectType
---@field CoffinMusumeCandle
---@field Teleport
---@field DestroyTrap
---@field HitBack
---@field SummonTrapOrHealByTrapBuffLayer number
---@field WeikeNotify number
SkillEffectType = {
    SkillEffectTypeStart = 1,
    Damage = 1, --普通伤害
    HitBack = 3, --击退(或拉回)
    ConvertGridElement = 4, --转色
    AddBuff = 5, --给目标加Buff
    AddGridEffect = 6, --给格子增加特殊效果(棱镜)
    LeaveEnterBattleField = 7, --离开进入战场
    Teleport = 8, ---瞬移
    Escape = 9, ---逃跑
    AbsorbPiece = 10, --吸收格子
    SummonTrap = 11, --召唤陷阱
    Rotate = 12, --旋转
    PullAround = 13, --拉到周围
    SerialKiller = 15, --连环杀人
    CalEdgePos = 16, --计算4个边界坐标
    StampDamage = 17, ---龙之印记伤害
    EachGridAddBuff = 18, ---每个格子产生buff
    --EddyTransport = 19, --传送漩涡
    DamageToBuffTarget = 19, --对具有特定buff的敌人造成伤害
    AddCollectDropNum = 20, --增加收集数
    DimensionTransport = 21, --任意门传送（需要使用拾取点信息）
    AddDimensionFlag = 22, --添加任意门标记（为 Team 加 DimensionFlag 组件，有这个组件的才会进行任意门传送点拾取）
    AddBloodOverFlow = 23, ---尤莱雅大招，恢复生命上限60%的血量，如果溢出则将最近的森格子变为强化森格子
    CreateDestroyGrid = 24, ---创建/销毁格子
    RandAttack = 25, ---刑拘娘的灵魂审判
    ShowWarningArea = 29, ---显示预警范围： 范围是配置的技能的攻击范围
    SummonEverything = 34, ---召唤一切
    AddBlood = 36, ---治疗回血
    EachGridAddBlood = 37, --根据格子数量治疗回血
    ResetGridElement = 58, ---重置格子，洗版，默认附带洗机关效果
    ConvertOccupiedGridElement = 62, -- 对技能范围内的实体*脚下*的格子转色
    SummonMultipleTrap = 64, --对范围内所有特定颜色的格子召唤机关
    --AdditionalChainRate = 65, --增加chain倍率
    Transport = 66, --运送实体
    MultiTraction = 67, --范围内目标牵引至中心
    SummonOnHitbackPosition = 68, --在目标被击退后的新位置面前召唤特定陷阱，效果改过
    MakePhantom = 69, --制造幻象
    AbsorbPhantom = 70, --吸收幻象，恢复血量
    Transformation = 71, --变身，改monsterID
    SacrificeTrapsAndDamage = 72, -- 吸收范围内特定的机关，根据吸收数量造成伤害
    AddRoundCount = 73,
    -- AdditionalSumon = 75, --在上一段技能召唤的格子中召唤机关 DISAVOWED
    ResetSelectGridElement = 76, --（扩展58）重置范围内某些符合选定规则的格子，比如龙女重置雷属性格子为其他格子
    ModifyBuffValue = 77, --修改某target身上某buff的某value
    DamageOnTargetCount = 78, -- 根据技能覆盖的目标数量决定伤害参数
    DestroyTrap = 79, -- 销毁机关
    SplashDamage = 80, -- 溅射攻击-以选中目标为中心计算另一个范围进行特殊公式伤害
    AngleFreeLineDamage = 81, -- 从施法者向点选位置连线，对范围内怪物造成伤害，要求配置指定pickupPos的索引
    IslandConvert = 82, -- 按2x2的pattern刷范围内的格子颜色
    -- ChangeAttribute = 83, -- 改变属性 DISAVOWED
    EnhanceOccupiedGrid = 84, -- 对目标占据的技能范围内的格子添加强化格子(或其他机关)
    CostCasterHP = 85, --扣除施法者自身血量,暂时只有按照当前血量百分比扣血
    ExChangeGridColor = 86, --交换两个格子的颜色
    ChangeElement = 87, -- 改变元素属性
    IsolateConvert = 88, --使目标孤立的转色
    RandDamageSameHalf = 89, ---对目标造成固定数量的伤害,重复打击的敌人伤害逐次减半
    DamageBasedOnTargetAttribute = 90, --根据技能目标属性判断是否造成伤害(目标血量低于30%追加伤害,弥加德)
    -- DamageLinkForTargetDeath = 91, --目标死亡时，将溢出的伤害平摊给拥有相同Buff的目标(艾希,觉醒3) DISAVOWED
    DamageBasedOnPickUpRect = 92, --根据施法者坐标和点选位置的矩形范围，计算伤害(渡 主动技)
    AddComboNum = 93, ---增加连线普攻combo数
    DeathBomb = 94, ---棺材娘大招打死的怪物会爆炸
    ConductDamage = 95,
    AttachMonster = 96, ---附身怪物
    DetachMonster = 97, ---脱离怪物
    HighFrequencyDamage = 98,
    MultipleScopesDealMultipleDamage = 99, --同一个目标在被技能范围覆盖多次，造成多次伤害
    RotateToPickup = 100,
    ResetSingleColorGridElement = 103, ---重置全场特定颜色的格子
    Suicide = 104, ---自杀
    ChangeBlockData = 105, --贴纸修改阻挡信息
    ForceMovement = 106, -- 强制位移，参见force_movement_calculator.lua
    ChangeGridPrism = 107, --棱镜机关修改棱镜数据
    SchummerHitback = 108, --舒默尔的特殊击退效果
    StickerLeave = 109, --贴纸离开转色处理
    GridPurify = 110, -- 格子净化
    DegressiveDirectionalDamage = 111, --直线递减伤害计算
    ConvertWithTrapRecord = 112, --使用机关记录的颜色转色，不通知buff转色
    TeleportAndSummonTrap = 113, ---根据血量瞬移位置，并召唤机关
    FrontExtendDegressiveDamage = 114, ---选取的第一个点为中心，选取第二个点作为方向，直线到版边。中间如果遇到指定机关，根据规则做扩展范围，扩展格子伤害递减（普律玛主动技）
    MarkGridInScope = 115, -- 标记一些格子，记录在entity身上。标记的效果取决于buff
    ChangeBuffLayer = 116, --修改buff层数
    SummonMeantimeLimit = 117, ---限制同时存在数量的召唤，当新的召唤成功后，如果同时存在的数量超过了限制，销毁最先召唤的。
    MoveTrap = 118, --移动机关
    MultipleDamageWithBuffLayer = 119, --根据施法者身上指定buff的层数，造成多次伤害
    DestroyMonster = 120, --销毁怪物，直接删除实体
    SealedCurse = 121, -- 尝试添加诅咒，包含目标为队长的逻辑处理
    DamageReflectDistance = 122, --根据反射距离计算伤害系数
    MonsterMoveGrid = 123, --怪物跟星灵一样连线行走逻辑
    KillPlayer = 124, --殺死玩家
    ResetGridElementNoNotify = 125, --重置格子不发任何通知
    DamageOnTargetDistance = 126, --造成伤害，根据目标的距离圈数提升伤害系数,初始从范围的中心点开始找，找下一个是从上一个选中的位置选
    AddBloodOverFlowForDamage = 127, ---恢复生命，如果溢出则将溢出的治疗量，给范围内的所有敌人造成伤害
    DamageBasedOnSectorAngle = 128, --在选择的扇形范围内，根据与主方向的夹角计算伤害
    SplashPreDamage = 129, -- 溅射攻击-以之前的每次伤害结果未知为中心计算另一个范围进行特殊公式伤害
    RotateByPickSector = 130, -- 根据两次点选确定旋转方向,进行旋转，参数配置角度（艾露玛主动技）
    SummonOnFixPosLimit = 131, ---根据配置的X个固定点，依次召唤Y个机关；若场上机关大于上限Z，则销毁最先召唤的
    SwitchBodyPart = 132, --切换Boss外形
    ChangePetTeamOrder = 133, --技能效果：光灵递补型换序
    ShufflePetTeamOrder = 134, --技能效果：打乱光灵出战顺序
    SwapPetTeamOrder = 135, --技能效果：交互光灵出战顺序
    VictoriaSuckBlood = 136, --维多利亚吸血
    GatherThrowDamage = 137, --鬼王技能：聚集范围内的指定类型怪和光灵，然后将光灵瞬移到指定范围内随机位置并造成伤害，杀死指定类型怪
    TriggerTrap = 138, --触发机关的触发技能
    AbsorbTrapsAndDamageByPickupTarget = 139, --根据点选对象选择是否吸收机关并造成伤害
    MoveBoard = 140, --移动棋盘
    MonsterMoveGridByMonsterElement = 141, --怪物按照属性选择一条跟属性相同颜色的尽量靠近目标的最短可行走路线。会触发机关
    EachTrapAddBlood = 142, --根据范围内机关数量治疗回血
    AddBuffByPickupTarget = 143, --根据点选对象选择附加buff
    RecoverFromGreyHP = 144, --从灰血池中按比例恢复生命值
    DecreaseSanByScope = 145, --根据技能范围选中的格子数扣除san值
    SingleGridFullDamage = 146, --范围内多次选中目标时，只有第一次计算造成全额伤害
    IncreaseSan = 147, --增加/减少san值
    LevelTrapAbsortSummon = 148, --清理范围内指定机关，在点选位置召唤一个等级为销毁的机关等级之合的新机关（N22光灵 法官 主动技）
    LevelTrapUpLevel = 149, --升级机关（N22光灵 法官 连锁技，销毁原机关，创建新机关）
    SwitchBodyAreaByTargetPos = 150, --根据目标位置旋转BodyArea
    TransferTarget = 151, --将目标数据传递给表现(SP薇丝 没有伤害的普攻)
    LevelTrapSummonOrUpLevel = 152, --如果位置上有等级机关，则升级机关，否则召唤一个（N22光灵 法官 觉醒被动）
    AlphaThrowTrap = 153, --阿尔法主动技1：阿尔法收集光灵位置十字范围内的机关或贝塔进行攻击并击退或击晕光灵
    AlphaBlinkAttack = 154, --阿尔法主动技2：阿尔法闪现攻击光灵然后瞬移后撤骑乘到机关上
    RideOn = 155, --骑乘机关或怪物
    MonsterMoveLongestGrid = 156, --怪物寻找最长路径，暂时只有米诺斯使用，包含一堆发送通知和造成伤害逻辑
    SacrificeTraps = 157, ---吸收范围内指定机关，并发送通知。
    DamageBySacrificeTraps = 158, --根据吸收机关的技能结果造成伤害。会造成多次伤害。
    MonsterMoveGridToSkillRangeFar = 159, --怪物按连线移动，向技能能攻击到目标的最远位置移动。会触发机关。（N18 世界boss克娜莉)
    DamageSamePosReduce = 160, --相同格子目标被打后伤害衰减，修改SkillFinal系数
    MonsterMoveGridFarthest = 161, --怪物按连线移动，向可及的最远位置移动。会触发机关。
    MultiplyBuffLayer = 162, --令目标身上指定层数翻倍
    TrapSummonMonster = 163, --召唤机关在自己上面召唤怪物
    RubikCube = 164, --魔方
    ChangeBodyArea = 165, --修改BodyArea
    DrawCard = 166, --抽卡 （光灵杰诺）
    MonsterMoveFrontAttack = 167, --怪向目标（队伍）移动 行为同ai moveFrontAttack 用于反制技能
    TransportByRange = 168, --主动技点选触发格子移动，如果第一个点选位置有单个怪那么也传送。
    PickUpTrapAndBuffDamage = 169, --根据选中地点指定机关上的指定buff层数来释放不同的伤害
    AddBuffByPickupBuffLayer = 170, --根据选中地点指定机关上的指定buff层数来给自己挂不同buff
    DamageTargetCanRepeat = 171, --根据选中地点指定机关上的指定buff层数来给自己挂不同buff
    ModifyAntiAttackParam = 172, --修改反制技能参数当前数值的效果
    RandomCountDamageSameHalf = 173, ---对目标造成随机数量的伤害,重复打击的敌人伤害逐次减半,和89的区别是，89是连锁技在用，是把所有目标统一传进去计算。如果89放到主动技，会造成有几个目标就算几次效果
    PetSacrificeSuperGridTraps = 174, ---光灵米洛斯 吸收范围内强化格子机关，并发送通知。
    PetMinosGhostDamage = 175, ---光灵米洛斯 幻影造成伤害 （伤害结果+幻影位置）
    CoffinMusumeCandle = 176, ---棺材娘技能3，根据指定ID的机关身上的指定buffValue（点亮状态）选择自己的行为
    DamageAndAddBuffByHitBack = 177, --根据击退结果造成伤害和添加buff
    CoffinMusumeSetCandleLight = 178, ---棺材娘蜡烛出生技，因初始加buff会被在错误的时机播放，改为技能实现
    SummonTrapByCasterPos = 179, ---全屏区域召唤，根据施法者所在区域进行筛检数量
    SnakeHeadMove = 180, ---贪吃蛇头部移动
    SnakeBodyMoveAndGrowth = 181, ---贪吃蛇身体移动和增长
    SnakeTailMove = 182, ---贪吃蛇尾部移动
    Transposition = 183, --互换位置
    SummonScanTrap = 184, --阿克希亚扫描模块-召唤扫描机关，并处理最大数量和依据施法者属性添加buff
    SummonTrapOrHealByTrapBuffLayer = 185, --阿克希亚QA主动技效果，根据点选位置上指定ID机关的指定层数回血
    KillTargets = 186, --杀死目标
    WeikeNotify = 187, --维克发送通知给小动物
    SetMonsterOffBoard = 188, --设置怪物离场状态 （符文刺客）
    MonsterMoveGridByParam = 189, --怪物按配置的参数连线移动
    SplashDamageAndAddBuff = 190, --以技能目标为溅射中心，造成伤害并附加buff，技能空放时使用配置的施法者偏移位置作为溅射中心
    DynamicCenterDamage = 191, --根据参数计算中心，在中心计算新的范围，选定目标进行伤害
    AddMoveScopeRecordCmpt = 192, --仲胥 给点选位置的机关/怪增加记录移动范围的组件，并记录点选位置对机关/怪中心位置的偏移
    EnterMirage = 193, --N26Boss：开启幻境
    TrapMoveAndDamage = 194, --N26Boss：子弹机关移动、移动中撞到玩家后爆炸
    ThrowMonsterAndDamage = 195, --N26Boss：主动技2，收集困字小怪并将困字小怪扔向玩家造成伤害
    DamageByBuffLayer = 196, -- 根据施法者Buff层数决定伤害参数
    TeleportTeamAroundAndSummonTrapLine = 197, ---瞬移位置到队伍周围一圈，朝向目标。从旧坐标连线到新坐标中心召唤机关，如果没有空位位置可以往外面找格子(n28蜘蛛)
    ConvertAndDamageByLinkLine = 198, ---N28光灵蒂娜：通过连线位移的方式进行转色及伤害，若造成伤害则瞬移至连线终点前的位置
    TurnToTargetChangeBodyAreaAndDir = 199, -- 朝向目标，中心点不变，修改自己身形和朝向，(n28蜘蛛3x2)
    ControlMonsterMove = 200, -- 控制目标怪物位移(n28蜘蛛)
    PetTrapMove = 201, --光灵机关移动
    SacrificeTargetNearestTrapsAndDamage = 202, -- 吸收距离目标最近的N个指定机关，根据吸收数量造成N次伤害
    DynamicScopeChainDamage = 203, --MSG59181 连锁技使用的是技能本体上的范围参数，而不是根据技能效果计算。连锁技现有的计算流程不支持，讨论后改为和191类似的方式临时处理。正式的处理方法看安排。
    NightKingTeleportPathDamage = 204, -- 夜王专属 在瞬移的每段路径（目标是）上计算范围，造成伤害，瞬移终点周围一圈造成伤害
    RefreshGridByBoardID = 205, ---N30Boss_斐桀洛 三技能：根据配置的地板ID来刷新格子
    SpliceBoard = 206, ---拼接棋盘,N31约书亚
    DamageBySelectPieceCount = 207, -- 根据选中颜色的格子数量造成伤害
    PopStar = 208, ---消灭星星玩法中的消除格子
    HighFrequencyDamage2 = 209, -- 高频伤害2,国服伊芙定制版本
    SummonFourAreaMonsterOnBoardEdge = 210, --召唤四格怪物在棋盘边上距离玩家最近的点
    PickUpGridTogether = 211, --点击格子聚拢效果
    ButterflySummon = 212, -- 神性蝴蝶召唤
    TankRushPerGrid = 213, -- N34启光坦克冲撞逻辑
    DamageByConvertGridCount = 214, --词条用使用buff存储的特定格子转色数量计算伤害
    DamageCountByBuffLayer = 215, --造成Buff层数次伤害
    DamageCountByBuffLayer2 = 216, --使用技能目标的Buff层数，造成特殊范围目标的Buff层数次伤害
    ControlMonsterCastHitBackTeam = 217, -- 控制目标怪物施法击退队伍
    SkillEffectTypeEnd = 999
}
---@class SkillAddBuffType
local SkillAddBuffType = {
    Default = 1, --默认是1个
    EachScopeGrid = 2, --技能范围里的每个格子都生成一个buff
    ByCostHPPercent = 3,
    BySurroundingTargetCount = 4,
    MultipleTimes = 5, --翻几倍
    LimitMaxCount = 6, --限制最高数量
    ByCasterTeamOrderDrop = 7 --根据NTTeamOrderChange内施法者下降的位置数添加
}
_enum("SkillAddBuffType", SkillAddBuffType)

---技能效果 加buff 概率计算方式扩展
---@class SkillAddBuffPropType
local SkillAddBuffPropType = {
    Default = 1, --默认 先整体计算概率 后选敌
    EachTargetByType = 2 -- 跳过整体计算概率，在选敌计算中各目标类型自行处理概率
}
_enum("SkillAddBuffPropType", SkillAddBuffPropType)

---@class SwitchBodyAreaType
local SwitchBodyAreaType = {
    TailFlick = 1, --夜王甩尾技能使用的旋转逻辑
    CounterAttack = 2, --夜王2阶段反制技能使用的旋转逻辑
    ByCasterDir = 3, --夜王2阶段技能2跃起使用，使用瞬移后的方向旋转BodyArea
    AfterTransformation = 4, --夜王变身刷新
    Refresh = 5, ---按照bodyArea刷新阻挡
    CoffinMusume = 6 ---棺材娘：类似3，但bodyArea是定制的
}
_enum("SwitchBodyAreaType", SwitchBodyAreaType)
