TriggerType = {
    None = 0, --不触发
    Always = 1, --无条件触发,只要收到通知就会触发
    Prob = 2, --概率触发,只要收到通知就会触发
    NotifyMe = 3, --通知的是自己
    MyTurn = 4, --通知时处于自己的回合
    NotifyMeProb = 5, --通知的是自己  概率触发
    PetNotify = 6, --宝宝触发
    LayerCount = 7, --buff叠加层数
    OwnerBlood = 8, --buff owner血量比较
    ProbMultiplyLayer = 9, --概率触发，概率=参数×层数
    CompareLayerCount = 10, --比较buff叠加层数
    BloodLessThan = 201, --血量小于x
    BloodMoreThan = 202, --血量大于x
    AttackElementMatch = 203, --攻击元素匹配
    TargetGridElementMatch = 204, --目标格子元素匹配
    DefenderElementMatch = 205, --被击元素匹配
    OwnerElementMatch = 207, --拥有者元素匹配
    Combo = 208, --combo数是x的倍数
    OwnerBuff = 209, --拥有者Buff匹配
    DefenderBuff = 210, --被击者Buff匹配
    BloodEqual = 211, --血量等于
    MonsterBodyArea = 212, --怪物体形 1单格 2多格
    MazeRoomType = 214, --房间类型
    MonsterAI = 215, --怪物AI匹配
    NotifyBuff = 216, --触发者Buff匹配，判断了notify是否等于owner
    SameCampInTeam = 217, --队伍中同阵营角色数量
    CountCycle = 218, --每x次触发一次
    DamageLargerThenRate = 219, --受到大于rate的伤害触发
    SpecificPetNormalHitMe = 220, --被特定的pet普攻
    TargetBodyAreaSubset = 221, --目标BodyArea子集（伤害效果）
    DefenderDistance = 222, --攻击者与被攻击者距离
    MonsterSkillDamageEnd = 224, --怪物释放完指定技能后
    ActiveSkillFirstHitRow = 225, --主动技打到的第一排坐标触发
    TargetPosIsSkillCenterPos = 226, ---攻击的目标是技能范围的中心
    MonsterClassIDMatch = 227, --指定怪物模版ID
    TargetBodyAreaSubsetBuff = 228, --目标BodyArea子集（加buff效果）
    MonsterKilled = 229, --怪物被击杀
    LimitAiRound = 230, --指定Ai回合
    TrapBombSummon = 231, ---炸弹生成器刷新
    RegularBodyMonster = 232, --常规怪
    SuperChain = 233, --超级连锁
    PieceTypeMatch = 234, -- notify传入的格子类型与配置相符
    TeleportOldPosInOwnerArea = 235, --传送技能的旧坐标在自己的范围内
    TeleportNewPosInOwnerArea = 236, --传送技能的新坐标在自己的范围内
    MonsterAIAliveCount = 237, --怪物AI匹配 存活数量
    TeamOwnerBuff = 238, --Team拥有的Buff
    NotifyTeamLeader = 239, --通知是队长
    TrapSkillMatch = 240, --机关释放技能
    FirstDeadPet = 241, --第一个死亡的星灵
    SkillIDMatch = 242, --技能匹配
    AfterPetTeleport = 243, --星灵使用瞬移效果后（事实上只会发生在主动技阶段）
    HasHPShield = 244, --拥有血条盾
    DamageOnAllMonsters = 245, --所有怪物都受到伤害
    PlayerDecreaseHp = 246, ---玩家掉血
    GameOver = 247, --战斗结束（胜利或失败）
    DefenderInCenterLine = 248, ---火车专用,被攻击者是否在攻击范围内中心的一条线上
    CheckLayer = 249, --判断发出通知的layer是否合法
    DefenderHPLessThan = 250, -- 受击者血量百分比的小于判定
    CampOrElementMatch = 251, --阵营或者元素匹配配置
    SlantNormalAttack = 252, --斜向普攻
    TeamOwnerDebuff = 253, --Team拥有Debuff
    OwnerDebuff = 254, --拥有者有Debuff
    DefenderDenuff = 255, --被击者有Debuff
    CompareChainPath = 256, --连锁数满足一种比较关系（仅适用于连锁相关的notify）
    CompMonsterType = 257, --判断生成的怪物类型,1表示全部2表示非Boss3表示只有Boss
    PossessedGridConverted = 258, --占据的格子被转成其他颜色
    ElementMatch = 259, --元素匹配配置
    NotifyMeOrTeam = 260, --通知的是自己或者队伍
    PieceEffectTypeMatch = 261, -- notify传入的格子材质类型与配置相符
    AtkHPPercentGreater = 262, ---攻击者血量百分比大于防御者
    DefHPPercentGreater = 263, ---防御者血量百分比大于攻击者
    NotifyOnlyBuff = 264, --触发者Buff匹配，只判断notify:GetNotifyEntity()
    TrapOnPos = 265, --机关在notify所传位置
    ChainSkillCount = 266, --连锁技阶段释放连锁技数量大于等于x
    NotifyMeEffectType = 267, ---通知的是自己的技能类型
    NotifySkill = 268, -- 通知的技能ID匹配
    NotifyEffectType = 269, -- 通知的技能效果匹配
    LayerBiggerThan = 270, --x层数超过y
    NotifyDefenderIsMe = 271, --通知的被打者是自己
    DefenderCount = 272, --比较目标数量
    CmpDeferHPAndAtkerAtk = 273, ---比较防御的血量和攻击者的攻击力
    OwnerNoBuff = 274, ---拥有者没有buff
    CmpDefenderHPPercent = 275, -- 受击者血量百分比的比较
    IsDefenderPlayer = 276,
    CompareSkillStageIndex = 277, --技能阶段比较
    TrapExist = 278, --存在指定机关
    MonsterAliveCount = 280, ---存活怪物数量
    DefenderNoBuff = 281, ---被击者没有buff
    TeamMovePieceTypeMatch = 282, -- 连线行走中，队长走过的格子颜色与配置相符
    PosPieceTypeMatch = 283, --位置格子颜色匹配
    IsAttachMonsterDead = 284, --附身的怪物死亡
    ChainPathTypeElement = 285, --连线颜色匹配
    PlayerHPRecovered = 286,
    BuffEffectMatch = 287, --buff效果匹配
    RemoveDuplicateDefender = 288, --去除重复的被击者
    NotifyEntityIsPetOrTrap = 289, --施法者是星灵或机关
    NotifyNotMe = 290, --通知者不是自己
    StickerNeedToDie = 291, --贴纸需要死亡
    PosInSpTrap = 292, --位移后停留在指定机关上面
    DefenderBodyAreaHasTrap = 293, --被击者身形位置有指定机关
    WaveNumMatch = 294, --波数匹配
    PosNoInSpTrap = 295, --位移后没有停留在指定机关上面
    AtkTargetPosMarkedByAttacker = 296, -- MarkGrid技能效果的联动机制
    SimpleHPMoreThan = 297, -- 202的简易版，去掉了通知目标的ID判断。类似逻辑请用其他trigger处理。
    ResetGridFlushTrapPosNoInMy = 298, --洗板后,脚下是否还有特殊机关,同步判断之前机关是否在我脚下
    SkillScopeCompareTargetCount = 299, --技能范围内对比目标数量
    NTTrapPosInMy = 300, ---机关死亡和出现通知的位置在我脚下
    DefenderHasMostBuffLayer = 301, ---被击者是拥有指定buff层数最多的怪物，层数大于0，层数相同选血量最多的
    CurseTowerIsActive = 302, --- 诅咒塔是激活状态
    OwnerGridPosChange = 303, --拥有者发生坐标变化
    ConvertSourceEffectType = 304, -- 配合NTGridConvert使用，判定转色的效果来源
    CompareLayerChange = 305, --比较层数变化0
    NotifyEntityIsOwnerSummonerEntity = 306, --buff通知的entity是buff持有者的召唤者
    CasterIsLegendPet = 307, --施法者是传说光灵
    IsAuroraTime = 308, --极光时刻
    TrapTriggerIsMyTeam = 309, --机关触发者是我的队伍
    NotifyFriendPetOrTeam = 310, --通知的是友方
    AttackerIsMeOrAttackerSuperIsMe = 311, ---施法者是我或者施法者的Super是我
    DonotCheckGameTurn = 312, --黑拳赛不要检查通知回合
    TeamLeaderMoveEndPosInRingRange = 313, --检测队长移动位置是否在以自身为中心的环内：移动过程中队长坐标始终在连线终点处，需要用notify的位置判断
    NotifyMeOrTeamPet = 314, --通知的是自己或队友
    ActiveSkillTag = 315, --技能标签（1伤害、2随机转色、3定向转色、4治疗、5位移）
    NotifyEntityIsSpecificPet = 316, --通知者是指定的星灵
    NotifyTrapLevelMatch = 317, --通知者是机关，并且机关层级匹配
    NotifyEntityInOwnerBodyArea = 318, --通知者的坐标在挂载者身形内
    TeamHasHPShield = 319, --队伍 拥有血条盾
    LayerCountDivisible = 320, --buff层数可被整除 参数1：buffId，参数2~.. 除数列表（任意一个满足则为true）
    ChainSkillStage = 321, --配合NTChainSkillAttackStart、NTChainSkillAttackEnd,判断连锁技是第几阶段
    TeamInSideSkillScope = 322, --队伍在技能范围内，范围计算使用buff挂载者，第二个参数默认1在范围内，0是不在范围内
    MoveEntityIsTeamOrPet = 323, --移动的/被击退的是队伍或者星灵
    DefenderListHasBuff = 324, --被击者列表中Buff匹配
    IsMeNewTeamLeader = 325, -- 自己是新的队长且不是原队长；参数1：不配置默认是新队长，1表示不是新队长
    OwnerPetIsTeamLeader = 326, --owner光灵当前是队长
    OwnerPetTeamOrderChangeType = 327, --本次队伍顺序变化中，owner光灵位置变化的正负值（1：向下 -1：向上 0：没变）
    NotifyIsOwnerSummonerTeamOrFriendPet = 328, --buff通知的entity是buff持有者的召唤者/所在的队伍/队友
    NotifyBuffEffectMatch = 329,
    DefenderIsMe = 330, --被击者是自己
    OwnerPetIsNotTeamTail = 331, --owner光灵自己是队尾
    PetInSkillScope = 332, --光灵在技能范围内：第一个参数为技能ID，范围计算使用Buff挂载者；第二个参数默认1在范围内，0不在范围内
    SanValueInRange = 333, --判断San值是否在区间
    PickUpPosIsTeamPos = 334, --点选的坐标是队伍的坐标
    IsOnMatchPieceTypeGrid = 335, --是否在指定颜色的格子上，第一个参数为指定的颜色
    CurDayNightState = 336, --昼夜模块 当前是白天（1）或黑夜（2） FeatureDayNightState
    SanChanged = 337, --判断san值是否增加或者减少，参数控制行为
    KilledByPet = 338, --Buff挂载者被光灵/光灵的SkillHolder，光灵召唤出来的东西所杀。都算光灵击杀
    PickUpPosMonsterBuffEffectMatch = 339, --点选的坐标上的怪物做buff匹配
    TargetPosMonsterBuffEffectMatch = 340, --目标坐标上的怪物做buff匹配
    SyncMovePosHasMonster = 341, --（机关）跟随移动，到达位置上有怪物
    SyncMovePosHasChanged = 342, --（机关）跟随移动，本次移动有位置变化（参数1：填1表示pathIndex为1时不判断位置变化）
    SanChangeHasDebtVal = 343, --San变化通知的debtValue 大于0 （扣到0后仍不足的部分）
    NotifyTrapIDMatch = 344, --通知者是机关，并且机关ID匹配
    RideState = 345, --骑乘状态 骑乘（1），未骑乘（2）
    IsMount = 346, --是否被骑乘
    IsTrapStateOpen = 347, --机关状态是否打开
    LayerCountNonDivisible = 348, -- 320的取反，只支持一个除数，可以指定0层时的行为
    LayerChangeCasterIsMe = 349, --82号通知专用，判断casterEntity是不是自己
    IsMeInvolvedInTeamLeaderChange = 350, --自己是*手动*换队长过程中的新队长或者旧队长
    ActiveSkillCausedDamage = 351, --配合30/104/48或类似时间使用，检查是否造成1次以上的非Miss伤害（需要看是否支持配合的伤害技能逻辑）
    FeatureSkillTypeMatch = 352, --配合模块技能相关通知，判断模块类型
    OwnerHasAllBuff = 353, ---buff的宿主身上有所有参数里的buff
    PlayerMovePosNotFirstStep = 354, ---光灵连线移动，chainPathIndex不是1（第一步是在原地）
    FirstNormalAttackDir = 355, ---是否首次朝配置方向普攻
    GridConvertMyPos = 356, ---转色结果包含我的脚下格子
    TargetAroundBodyAreaCompareMonsterCount = 357, --攻击目标的身形几圈内，对比包含活着非自己怪物的数量（无视不可被选择为目标等buff）
    ActiveSkillPowerfullRound = 358, ---主动技已就绪的回合数匹配
    TeamInAuraRange = 359, --队伍在光环范围内，第一个参数为光环组ID，第二个参数默认1在范围内，0是不在范围内
    PetMoveInRange = 360, ---光灵移动到指定范围内。
    CoffinMusumeCandleLight = 361, ---棺材娘的蜡烛专用：判断自己的亮灭状态
    PosInAuraRange = 362, ---通知的对象位置在光环内，第一个单数为光环组ID，第二个参数为光环层数，第三个参数默认1在范围内，0不在范围内
    MonsterCompareDistance = 363, --与指定的怪物比较距离队伍的距离
    HowManyKindsOfElementInTeam = 364, --队伍中不同属性光灵总数判断
    TrapSummonerHasSummonedBefore = 365, ---机关的召唤者之前是否召唤了
    TrapSummonedByMe = 366, ---机关召唤者是不是自己
    NotifyDefenderBodyAreaMatch = 367, --通知的被打者（怪）体型匹配 黑拳赛时敌方队伍算单格怪
    WeikeNotifySkillType = 368, ---维克的小动物专属通知的技能类型判定
    AttackTargetVisibleBuffCount = 369, ---NotifyAttackBase的受击者身上可见buff的数量判定
    DefenderRingDistance = 370, ---按圈计算的222
    IsMeHPLocked = 371, --通知时刻自己是否处于锁血状态
    IsSkillSelectTargetModeMatch = 372, ----伤害技能的选敌类型匹配 0：格子类型 1：单体类型
    PetIDInTeam = 373, ---队伍内是否有指定ID的光灵
    ChainSkillIndex = 374, ---对应ChainSkillAttackEnd，判断数据内的连锁技index
    MonsterInAuraRange = 375, --通知的怪物在光环范围内，第一个参数为光环组ID，第二个参数默认1在范围内，0是不在范围内，第三个参数判断是否是BOSS，默认0不是BOSS，1是BOSS
    GridConvertHasWater = 376, ---转色通知的格子有水格子，和NTGridConvert绑定
    TeamEnterExitAuraRange = 377, --队伍是否进入或退出光环范围
    IsEquipRefineUIStateMatch = 378, --装备精炼局内UI开关状态是否匹配 参数1：开关状态
    IsControlOrMoveHost = 379, --是否是宿主被控制或位移（击退、牵引）
    IsDefenderBodyMatchOrCannotBeHitBack = 380, --被击者体型匹配或不可被位移（一般性检查，只检测无敌、击退、免控）
    CheckCountDown = 381, --检查buff触发倒计时
    HasMonsterAroundDefender = 382, --被击者周围范围（可用技能id配置范围）内有怪
    FmodLevelTotalRoundCount = 383, --总回合数的余数
    OwnerAroundCompareTrapCount = 384, --挂载者周围比较指定机关数量
    ActiveSkillCostCasterHPNoZero = 385, --NTActiveSkillCostCasterHPEnd GetDamage() 大于0
    BloodChange =386, ---判断血量变化 1：血量增加 2：血量减少
    PopStarScoreNoLess = 387, --消灭星星当前总得分不小于参数一
    PetActiveSkillReady = 388, --光灵主动技就绪
    OwnerPetIsTeamLeaderOrChainPathTypeElement = 389, --owner光灵当前是队长 or 连线颜色匹配
    PopStarPopNumNoLess = 390, --消灭星星本次消除得分不小于参数一
    PlayerEachMoveEndRangeHasMonster = 391, --36号通知位置为中心，计算专门的范围，判断范围内是否有怪物
    PlayerEachMoveEndRangeHasTrapByTypeOrMonster = 392, --36号通知位置为中心，计算专门的范围，判断范围内是否有指定类型的机关
    CurseHpOverRedHp = 393, --诅咒血量超过了当前血量
    DefenderHasAttackerAddIconBuff = 394, --被击者有攻击者添加的显示图标的Buff
    RoundFirstActiveSkill = 395, --回合第一次主动技
    PetSex = 396, --光灵性别
    PetSexUpAndDown = 397,--光灵在队伍中前后性别是否符合
    DefenderBeHitBackOrTraction = 398, --被击者被击退或者牵引
    AllMonsterHaveCampType = 399, --场上存在指定阵营的怪物
    MonsterClassIDMatchDefender = 400, --指定怪物模版ID
    BreakHPLockIsUnlockHP = 401,    --锁血状态是由UnlockHP造成的
    NotHaveBattleLevelResult = 402, --战斗还未结束
    NoCurseHp = 403, --身上没有诅咒血条
    CheckConvertGridSkillType = 404, --检查转色技能类型
    CheckConvertGridHasGridType = 405, --检查转色技能是否有指定类型的格子
    NotifyMeOrSuperMe = 406,---通知者是自己或者super是自己
    TeamInActiveSkillScope = 407,   --队伍在当前释放的主动技范围内
    IsBuffHasRoundCountAndIcon = 408, --MSG69936，初版需配合通知62
    AllMonsterNotHaveCampType = 409, --场上不存在指定阵营的怪物
    NotifyIsMyTeam = 410, --通知的NotifyEntity是不是buff宿主的队伍，MSG69031
    CompareCount = 2181 --当前保存的触发数与参数2相比较，满足参数1所指定的比较关系时
}
