---@class UIHauteCoutureDrawDynamicProbabilityBgKR:UICustomWidget
_class("UIHauteCoutureDrawDynamicProbabilityBgKR", UICustomWidget)
UIHauteCoutureDrawDynamicProbabilityBgKR = UIHauteCoutureDrawDynamicProbabilityBgKR

function UIHauteCoutureDrawDynamicProbabilityBgKR:Constructor()
end