---@class UIHauteCoutureDuplicateRewardBgBLH:UICustomWidget
_class("UIHauteCoutureDuplicateRewardBgBLH", UICustomWidget)
UIHauteCoutureDuplicateRewardBgBLH = UIHauteCoutureDuplicateRewardBgBLH

function UIHauteCoutureDuplicateRewardBgBLH:Constructor()
end
